//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KresBasvuruGoruntule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakanin_Bilgisi
    {
        public int Bakan_Id { get; set; }
        public Nullable<int> Cocuk_Id { get; set; }
        public string Emekli_Personel_Torun { get; set; }
        public string Bakan_TC_No { get; set; }
        public string Bakan_Telefon_Numarasi { get; set; }
    
        public virtual Cocuk_Bilgisi Cocuk_Bilgisi { get; set; }
    }
}
