//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KresBasvuruGoruntule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cocuk_Harici_Bilgi
    {
        public int Harici_Bilgi_Id { get; set; }
        public Nullable<int> Cocuk_Id { get; set; }
        public string Cocuk_Kronik_Hastalik { get; set; }
        public string Cocuk_Alerji { get; set; }
        public string Cocuk_Davranis_Problemi { get; set; }
        public string Cocuk_Ozel_Durum { get; set; }
    
        public virtual Cocuk_Bilgisi Cocuk_Bilgisi { get; set; }
    }
}
