//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KresBasvuruGoruntule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILCELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILCELER()
        {
            this.MAHALLEs = new HashSet<MAHALLE>();
        }
    
        public int ID { get; set; }
        public string ILCELER1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAHALLE> MAHALLEs { get; set; }
    }
}
