//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KresBasvuruGoruntule
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAHALLE
    {
        public int ID { get; set; }
        public string MAHALLE1 { get; set; }
        public Nullable<int> ILCE_ID { get; set; }
    
        public virtual ILCELER ILCELER { get; set; }
    }
}
